const Joi = require('joi');

export default uservalidation = Joi.object({
    username: Joi.string().alphanum().min(3).max(30).required(),
    email: Joi.string().email().required(),
    banglaName: Joi.string().min(6).max(30).required(),
    englishName: Joi.string().min(6).max(30).required(),
    grade: Joi.string().min(1).max(10).required(),
    class: DataTypes.STRING,
    idNo: DataTypes.STRING,
    password: DataTypes.STRING,
    batchNo: DataTypes.STRING,
    nid: DataTypes.STRING,
    cadre: DataTypes.STRING,
    workingArea: DataTypes.STRING,
    section: DataTypes.STRING,
    fatherName: DataTypes.STRING,
    motherName: DataTypes.STRING,
    dateOfJoin: DataTypes.DATE,
    dateOfBirth: DataTypes.DATE,
    prlStartDate: DataTypes.DATE,
    branch: DataTypes.STRING,
    maritalStatus: DataTypes.STRING,
    highestEducationLevel: DataTypes.STRING,
    gender: DataTypes.STRING,
    bloodGroup: DataTypes.STRING,
    personalMail: Joi.string().email().required(),
    officialMail: Joi.string().email().required(),
    personalNumber: DataTypes.STRING,
    otp: DataTypes.STRING,
    officialNumber: DataTypes.STRING,
    status: DataTypes.STRING,
    designation: DataTypes.STRING,
    telephone: DataTypes.STRING,
    role: DataTypes.STRING,
});