const Joi = require('joi');

export default uservalidation = Joi.object({
    username: Joi.string().alphanum().min(3).max(30).required(),
    email: Joi.string().email().required(),
    banglaName: Joi.string().min(6).max(30).required(),
    englishName: Joi.string().min(6).max(30).required(),
    grade: Joi.string().min(1).max(10).required(),
    class: Joi.string().min(1).max(10).required(),
    idNo: Joi.string().min(1).max(10).required(),
    password: Joi.string().min(1).max(10).required(),
    batchNo: Joi.string().min(1).max(10).required(),
    nid: Joi.string().min(1).max(10).required(),
    cadre: Joi.string().min(1).max(10).required(),
    workingArea: Joi.string().min(1).max(10).required(),
    section: Joi.string().min(1).max(10).required(),
    fatherName: Joi.string().min(4).max(10).required(),
    motherName: Joi.string().min(1).max(10).required(),
    dateOfJoin: Joi.string().min(1).max(10).required(),
    dateOfBirth: Joi.string().min(1).max(10).required(),
    prlStartDate: Joi.string().min(1).max(10).required(),
    branch: Joi.string().min(1).max(10).required(),
    maritalStatus: Joi.string().min(1).max(10).required(),
    highestEducationLevel: Joi.string().min(1).max(10).required(),
    gender: Joi.string().min(1).max(10).required(),
    bloodGroup: Joi.string().min(1).max(10).required(),
    personalMail: Joi.string().email().required(),
    officialMail: Joi.string().email().required(),
    personalNumber: Joi.string().min(1).max(10).required(),
    otp: DataTypes.Joi.string().min(1).max(10).required(),
    officialNumber: Joi.string().min(1).max(10).required(),
    status: Joi.string().min(1).max(10).required(),
    designation: Joi.string().min(1).max(10).required(),
    telephone: Joi.string().min(1).max(10).required(),
    role: Joi.string().min(1).max(10).required(),
});